dist: xenial
sudo: required
language: c
compiler:
  - gcc
before_install:
  - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - libsdl2-dev
  coverity_scan:
    project:
      name: "sobomax/digger"
      description: "Classic Game of Digger"
    notification_email: sobomax@gmail.com
    build_command_prepend: "make clean"
    build_command: "make all"
    branch_pattern: coverity_scan
env:
  global:
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    #   via the "travis encrypt" command using the project repo's public key
    - secure: "gF2NmAF8u3ajNVmX6a+BSOtdQmZfAPog7wCdNeDHXJrCwecVA8f1tx5ZuJVpHCCdtQDueAy32IU2k8POkwP+8Vl6obLzo1m9EITRLYkCdfzPTCGz/kPRLSvabsaSZR9eFvycUkTC805H39S5Wjogys6cfJwAVhWYmzH8Gvfb03k="
script:
  - TEST_TYPE=short make do-test
