dist: xenial
sudo: required
language: c
compiler:
  - clang
  - gcc
before_install:
  - pip install --user cpp-coveralls

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - cmake-data
      - gcc-5
      - libsdl2-dev
env:
  global:
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    #   via the "travis encrypt" command using the project repo's public key
    - secure: "gF2NmAF8u3ajNVmX6a+BSOtdQmZfAPog7wCdNeDHXJrCwecVA8f1tx5ZuJVpHCCdtQDueAy32IU2k8POkwP+8Vl6obLzo1m9EITRLYkCdfzPTCGz/kPRLSvabsaSZR9eFvycUkTC805H39S5Wjogys6cfJwAVhWYmzH8Gvfb03k="
script:
  - make do-test
