sudo: required
language: c
compiler:
  - clang
  - gcc
addons:
  apt:
    packages:
      - cmake
      - cmake-data
matrix:
  include:
  - name: "GNU Make"
    env: TARGET="do-test"
  - name: "CMake"
    env: TARGET="do-test-cmake"
script:
    make "${TARGET}"
