sudo: required
language: c
compiler:
  - clang
  - gcc
before_install:
  - pip install --user cpp-coveralls
addons:
  apt:
    packages:
      - cmake
      - cmake-data
env:
  - TARGET="do-test"
  - TARGET="do-test-cmake"
script:
    make "${TARGET}"
