sudo: required
language: c
compiler:
  - clang
  - gcc
before_install:
  - pip install --user cpp-coveralls
addons:
  apt:
    packages:
      - cmake
      - cmake-data
env:
  - MAKE_ENV="CI_COVERAGE=1" TARGET="do-test"
  - TARGET="do-test-cmake"
script:
  - make ${MAKE_ENV} "${TARGET}"
after_success:
  - coveralls --exclude CMakeFiles --gcov-options '\-lp'
