version: 1.0.{build}
build_script:
- cmd: >-
    set MINGW=C:\mingw-w64\i686-6.3.0-posix-dwarf-rt_v5-rev1\mingw32


    set PATH=%MINGW%\bin;C:\MinGW\msys\1.0\bin;%PATH%

    set ARCH=MINGW

    set WINDRES=windres


    echo === Download zlib ==================================================

    cd ..

    wget http://zlib.net/zlib128-dll.zip

    mkdir zlib-1.2.8

    cd zlib-1.2.8

    unzip ../zlib128-dll.zip

    cd ..


    echo === Download SDL ===================================================

    curl -s https://www.libsdl.org/release/SDL2-devel-2.0.5-mingw.tar.gz | tar -xz


    echo === Build Digger ===================================================

    cd digger

    make


    echo === Create Artifact ================================================

    copy ..\zlib-1.2.8\zlib1.dll

    copy ..\SDL2-2.0.5\i686-w64-mingw32\bin\SDL2.dll


    zip -j digger-win32.zip digger.exe digger.txt zlib1.dll SDL2.dll
artifacts:
- path: digger-win32.zip
