name: CI
on: [push, pull_request]

jobs:
  build-windows-msys2-mingw:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include: [
          { msystem: MINGW64, msystem_lower: mingw64, arch: x86_64 }
          ,{msystem: MINGW32, msystem_lower: mingw32, arch: i686   }
        ]          
    steps:
      - uses: actions/checkout@v1
        with:
          path: temp
          fetch-depth: 0
      - uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.msystem }}
          install: mingw-w64-${{ matrix.arch }}-toolchain mingw-w64-${{ matrix.arch }}-SDL2 mingw-w64-${{ matrix.arch }}-pkg-config
          update: true
      - name: Update
        run: |
          msys2 -c 'pacman --noconfirm -Suuy'
          msys2 -c 'pacman --noconfirm -Suu'
      - name: Build
        run: |
          make
        shell: cmd
        env:
          CC: gcc
          CXX: g++
          PATH: D:\a\_temp\msys\msys64\usr\bin;D:\a\_temp\msys\msys64\${{ matrix.msystem_lower }}\bin;D:\a\_temp\msys
# TODO(#20): no CI on macos
# TODO(#21): no CI on freebsd
